import ParsedAppSettingsEntity from "./parsed-applications-settings.entity"

export default interface ParsedAppEntity {
  App_name: string
  App_Likes: number
  App_Picture: string
  App_Views: string
  App_Rating: string | number

  App_Settings: ParsedAppSettingsEntity | undefined

  links_Tags_1_Tags: string
  links_Tags_2_Tags: string
  links_Tags_3_Tags: string
  links_Tags_4_Tags: string
  links_Tags_5_Tags: string
  links_Tags_6_Tags: string
  links_Tags_7_Tags: string
  links_Tags_8_Tags: string
  links_Tags_9_Tags: string
  links_Tags_10_Tags: string
  links_Tags_11_Tags: string
  links_Tags_12_Tags: string
  links_Tags_13_Tags: string
  links_Tags_14_Tags: string
  links_Tags_15_Tags: string
  links_Tags_16_Tags: string
  links_Tags_17_Tags: string
  links_Tags_18_Tags: string
  links_Tags_19_Tags: string
  links_Tags_20_Tags: string
  links_Tags_21_Tags: string
  links_Tags_22_Tags: string
  links_Tags_23_Tags: string
  links_Tags_24_Tags: string
  links_Tags_25_Tags: string
  links_Tags_26_Tags: string
  links_Tags_27_Tags: string
  links_Tags_28_Tags: string
  links_Tags_29_Tags: string
  links_Tags_30_Tags: string
  links_Tags_31_Tags: string
  links_Tags_32_Tags: string
  links_Tags_33_Tags: string
  links_Tags_34_Tags: string
  links_Tags_35_Tags: string
  links_Tags_36_Tags: string
  links_Tags_37_Tags: string
  links_Tags_38_Tags: string
  links_Tags_39_Tags: string
  links_Tags_40_Tags: string
  links_Tags_41_Tags: string
  links_Tags_42_Tags: string
  links_Tags_43_Tags: string
  links_Tags_44_Tags: string
  links_Tags_45_Tags: string
  links_Tags_46_Tags: string
  links_Tags_47_Tags: string
  links_Tags_48_Tags: string
  links_Tags_49_Tags: string
  links_Tags_50_Tags: string

  links_Links_1_name: string
  links_Links_1_url: string
  links_Links_2_name: string
  links_Links_2_url: string
  links_Links_3_name: string
  links_Links_3_url: string
  links_Links_4_name: string
  links_Links_4_url: string
  links_Links_5_name: string
  links_Links_5_url: string
  links_Links_6_name: string
  links_Links_6_url: string
  links_Links_7_name: string
  links_Links_7_url: string
  links_Links_8_name: string
  links_Links_8_url: string
  links_Links_9_name: string
  links_Links_9_url: string
  links_Links_10_name: string
  links_Links_10_url: string
  links_Links_11_name: string
  links_Links_11_url: string
  links_Links_12_name: string
  links_Links_12_url: string
  links_Links_13_name: string
  links_Links_13_url: string
  links_Links_14_name: string
  links_Links_14_url: string
  links_Links_15_name: string
  links_Links_15_url: string
  links_Links_16_name: string
  links_Links_16_url: string
  links_Links_17_name: string
  links_Links_17_url: string
  links_Links_18_name: string
  links_Links_18_url: string
  links_Links_19_name: string
  links_Links_19_url: string
  links_Links_20_name: string
  links_Links_20_url: string
  links_Links_21_name: string
  links_Links_21_url: string
  links_Links_22_name: string
  links_Links_22_url: string
  links_Links_23_name: string
  links_Links_23_url: string
  links_Links_24_name: string
  links_Links_24_url: string
}
